import React, { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { ItemType } from '@/types/index';

interface LabelPreviewProps {
    item: ItemType | null;
    quantity: number;
}

/**
 * Generate a sample EPC hex for preview
 * This is a simplified version - actual EPCs are generated by the backend
 */
function generateSampleEPCHex(code: string, serialNumber: number): string {
    // Simplified EPC hex generation for preview
    // Format: Header (2 chars) + Filter/Partition (1 char) + Company Prefix (10 chars) + Item Ref (1 char) + Serial (10 chars)
    const header = '30'; // SGTIN-96 header
    const filterPartition = '6'; // Filter 1, Partition 6
    const companyPrefix = '0000000000'; // 10 chars (simplified)
    const itemRef = (parseInt(code.slice(-1)) || 1).toString(16).padStart(1, '0');
    const serial = serialNumber.toString(16).padStart(10, '0').slice(-10);

    return (header + filterPartition + companyPrefix + itemRef + serial).toUpperCase().padEnd(24, '0');
}

const LabelPreview: React.FC<LabelPreviewProps> = ({
    item,
    quantity,
}) => {
    // Generate a sample EPC hex if not provided
    const displayEPC = useMemo(() => {
        return {
            epcHex: generateSampleEPCHex(item?.code || '', 1),
            serialNumber: 1,
        };
    }, [item?.code]);

    // Label dimensions: 60mm x 40mm
    // At 203 DPI: 60mm = 2.362" × 203 = 480 dots, 40mm = 1.575" × 203 = 320 dots
    const labelWidth = 480; // dots (60mm at 203 DPI)
    const labelHeight = 320; // dots (40mm at 203 DPI)
    const scale = 0.8; // Scale for preview display

    return (
        <Card className="w-full">
            <CardHeader>
                <CardTitle>Label Preview</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="text-sm text-muted-foreground">
                    Preview of how the label will appear (Sample: Label 1 of {quantity})
                </div>

                {/* Label Preview Container */}
                <div className="border-2 border-dashed border-gray-300 bg-gray-50 p-4 rounded-md">
                    <div className="text-xs text-center text-muted-foreground mb-2">
                        Label Preview (Scaled)
                    </div>
                    <div
                        className="bg-white border-2 border-gray-400 shadow-md mx-auto"
                        style={{
                            width: `${labelWidth * scale}px`,
                            minHeight: `${labelHeight * scale}px`,
                            padding: '8px',
                            fontFamily: 'monospace',
                            position: 'relative',
                        }}
                    >
                        {/* Label Content - Single label preview (60mm x 40mm) */}
                        <div className="flex flex-col h-full justify-between gap-2">
                            {/* Top section with logo */}
                            <div className="flex items-start justify-between gap-2">
                                <div className="space-y-2 flex-1 border-b border-gray-400 pb-2">
                                    <div className="text-sm font-bold" style={{ fontSize: '18px', lineHeight: '1.2' }}>
                                        Production Line {item?.productionLine?.name || 'N/A'}
                                    </div>
                                    <div className="text-xs" style={{ fontSize: '14px', lineHeight: '1.3' }}>
                                        Item: {item?.code || 'N/A'}
                                    </div>
                                    <div className="text-xs truncate" style={{ fontSize: '12px', lineHeight: '1.3' }}>
                                        {item?.description1 || 'N/A'}
                                    </div>
                                    <div className="text-xs truncate" style={{ fontSize: '12px', lineHeight: '1.3' }}>
                                        {item?.description2 || 'N/A'}
                                    </div>
                                </div>
                                {/* Logo positioned on the right */}
                                <div className="flex-shrink-0 absolute right-0 top-4" style={{ width: '120px', height: '120px' }}>
                                    <img
                                        src="/logo.png"
                                        alt="Company Logo"
                                        className="w-full h-full object-contain"
                                        style={{ maxWidth: '100%', maxHeight: '100%' }}
                                    />
                                </div>
                            </div>

                            {/* Middle section */}
                            <div className="space-y-1.5 border-b border-gray-400 pb-2 mb-2">
                                <div className="text-xs font-semibold" style={{ fontSize: '14px', lineHeight: '1.2' }}>
                                    Label 1/{quantity}
                                </div>
                                <div className="text-xs" style={{ fontSize: '12px', lineHeight: '1.2' }}>
                                    Serial: {displayEPC.serialNumber}
                                </div>
                                <div className="text-xs font-mono break-all leading-tight" style={{ fontSize: '12px', wordBreak: 'break-all' }}>
                                    {displayEPC.epcHex}
                                </div>
                            </div>

                            {/* Bottom section - Barcode */}
                            <div className="flex items-end justify-end mt-2">
                                <div className="flex flex-col items-end gap-1">
                                    <div className="flex gap-0.5 items-end">
                                        {/* Simulated barcode pattern */}
                                        {[2, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 3, 1, 1, 2, 1, 1, 2, 3, 1, 2, 1, 1].map((width, i) => (
                                            <div
                                                key={i}
                                                className="bg-black"
                                                style={{
                                                    width: `${width * 1.5}px`,
                                                    height: '20px',
                                                }}
                                            />
                                        ))}
                                    </div>
                                    <span className="text-xs" style={{ fontSize: '8px' }}>
                                        {item?.code || 'N/A'}-{displayEPC.serialNumber}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Label Specifications */}
                <div className="text-xs text-muted-foreground space-y-1">
                    <div>
                        <strong>Label Size:</strong> 60mm × 40mm ({labelWidth} × {labelHeight} dots at 203 DPI)
                    </div>
                    <div>
                        <strong>Total Labels:</strong> {quantity}
                    </div>
                    <div>
                        <strong>EPC Format:</strong> SGTIN-96 (Hex: {displayEPC.epcHex.length} characters)
                    </div>
                </div>

                <Separator />
            </CardContent>
        </Card>
    );
};

export default LabelPreview;
